[package]
name = "matcher-rs"
version = "0.1.0"
authors = ["rensiyuan"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "issuance"
path = "src/bin/issuance.rs"

[[bin]]
name = "presentation"
path = "src/bin/presentation.rs"

[dependencies]
nanoserde = "0.1"
base64 = "0.22"
log = "0.4"

[features]
default = ["static_log_off"]
static_log_off = ["log/max_level_off"]
logging = []

[build-dependencies]

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
lto = true
